export const LOAD_TASKS = 'LOAD_TASKS';
export const TASKS_LOADED = 'TASKS_LOADED';
export const TASKS_LOADING_ERROR = 'TASKS_LOADING_ERROR';

export const LOAD_SINGLE_TASK = 'LOAD_SINGLE_TASK';
export const SINGLE_TASK_LOADED = 'SINGLE_TASK_LOADED';
export const SINGLE_TASK_LOADING_ERROR = 'SINGLE_TASK_LOADING_ERROR';

export const ADD_TASK = 'ADD_TASK';
export const TASK_ADDED = 'TASK_ADDED';
export const TASK_ADDING_ERROR = 'TASK_ADDING_ERROR';

export const DELETE_TASK = 'DELETE_TASK';
export const TASK_DELETED = 'TASK_DELETED';
export const TASK_DELETING_ERROR = 'TASK_DELETING_ERROR';

export const UPDATE_TASK = 'UPDATE_TASK';
export const TASK_UPDATED = 'TASK_UPDATED';
export const TASK_UPDATING_ERROR = 'TASK_UPDATING_ERROR';

export const UPDATE_TASK_POSITION = 'UPDATE_TASK_POSITION';
export const TASK_POSITION_UPDATED = 'TASK_POSITION_UPDATED';
export const TASK_POSITION_UPDATING_ERROR = 'TASK_POSITION_UPDATING_ERROR';

export const DUE_BASE_TIME_FORMAT = 'YYYY-MM-DD HH:mm:ss';

export const RESET_TASKS = 'RESET_TASKS';
