export const LOAD_PROJECTS = 'LOAD_PROJECTS';
export const PROJECTS_LOADED = 'PROJECTS_LOADED';
export const PROJECTS_LOADING_ERROR = 'PROJECTS_LOADING_ERROR';

export const ADD_PROJECT = 'ADD_PROJECT';
export const PROJECT_ADDED = 'PROJECT_ADDED';
export const PROJECT_ADDING_ERROR = 'PROJECT_ADDING_ERROR';

export const DELETE_PROJECT = 'DELETE_PROJECT';
export const PROJECT_DELETED = 'PROJECT_DELETED';
export const PROJECT_DELETING_ERROR = 'PROJECT_DELETING_ERROR';

export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const PROJECT_UPDATED = 'PROJECT_UPDATED';
export const PROJECT_UPDATING_ERROR = 'PROJECT_UPDATING_ERROR';
