export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export const SETTINGS_LOADED = 'SETTINGS_LOADED';
export const SETTINGS_LOADING_ERROR = 'SETTINGS_LOADING_ERROR';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const SETTINGS_UPDATED = 'SETTINGS_UPDATED';
export const SETTINGS_UPDATING_ERROR = 'SETTINGS_UPDATING_ERROR';

export const RESET_SETTINGS = 'RESET_SETTINGS';
