swagger: "2.0"
info:
  version: "0.1.0"
  title: pm-app
#basePath: /api/v1
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /user:
    x-swagger-router-controller: user
    get:
      description: Get information baout the user
      operationId: user
      consumes:
        - application/json
      responses:
        200:
          description: User info
          schema:
            $ref: '#/definitions/User'
        "500":
          description: Internal error
          schema:
            $ref: '#/responses/Error'

  /user/login:
    x-swagger-router-controller: user
    put:
      description: Login user
      operationId: login
      consumes:
        - application/json
      responses:
        200:
          description: User logged in
        "500":
          description: Internal error
          schema:
            $ref: '#/responses/Error'

  /settings:
    x-swagger-router-controller: settings
    put:
      description: Settings for the current user
      operationId: all
      consumes:
        - application/json
      responses:
        200:
          description: Settings object
        "500":
          description: Internal error
          schema:
            $ref: '#/responses/Error'

parameters:
  projectId:
    in: path
    name: projectId
    required: true
    type: integer
    description: The project ID
  taskId:
    in: path
    name: taskId
    required: true
    type: integer
    description: The task ID
  boardId:
    in: path
    name: boardId
    required: true
    type: integer
    description: The board ID

responses:
  Error:
    description: Error
    schema:
      required:
        - message
      properties:
        message:
          type: string

definitions:
  User:
    properties:
      email:
        type: string
      username:
        type: string
  # I use ListItem as general definition for lists of tasks in project
  # and list of projects in single task
  ListItem:
    properties:
      id:
        type: integer
      name:
        type: string
  Task:
    required:
      - name
    properties:
      id:
        type: integer
      name:
        type: string
      description:
        type: string
      done:
        type: boolean
      added:
        type: string
        format: date
      updated:
        type: string
        format: date
      board_id:
        type: integer
      id_position_scrum:
        type: integer
      projects:
        type: array
        items:
          $ref: '#/definitions/ListItem'
  Project:
    required:
      - name
    properties:
      id:
        type: integer
      name:
        type: string
      description:
        type: string
      added:
        type: string
        format: date
      updated:
        type: string
        format: date
      tasks:
        type: array
        items:
          $ref: '#/definitions/ListItem'
  Board:
    required:
      - name
    properties:
      id:
        type: integer
      name:
        type: string
      description:
        type: string
      id_position:
        type: integer
