export const LOAD_BOARDS = 'LOAD_BOARDS';
export const BOARDS_LOADED = 'BOARDS_LOADED';
export const BOARDS_LOADING_ERROR = 'BOARDS_LOADING_ERROR';

export const ADD_BOARD = 'ADD_BOARD';
export const BOARD_ADDED = 'BOARD_ADDED';
export const BOARD_ADDING_ERROR = 'BOARD_ADDING_ERROR';

export const UPDATE_BOARD = 'UPDATE_BOARD';
export const BOARD_UPDATED = 'BOARD_UPDATED';
export const BOARD_UPDATING_ERROR = 'BOARD_UPDATING_ERROR';

export const DELETE_BOARD = 'DELETE_BOARD';
export const BOARD_DELETED = 'BOARD_DELETED';
export const BOARD_DELETING_ERROR = 'BOARD_DELETING_ERROR';
