export const TASKS_LOADED = 'TASKS_LOADED';
export const TASKS_ADDED = 'TASKS_ADDED';
export const TASK_DELETED = 'TASK_DELETED';
export const TASK_UPDATED = 'TASK_UPDATED';
export const UPDATE_TASK_POSITIONS_AFTER_DRAGGING = 'UPDATE_TASK_POSITIONS_AFTER_DRAGGING';
export const DUE_BASE_TIME_FORMAT = 'YYYY-MM-DD HH:mm:ss';
